server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

#-- 사용할 다국어파일의 메세지파일 이름을 messages로 함
spring:
  messages:
    basename: messages


  #-- Database 설정 (Failed to determine a suitable driver class 에러는 이부분을 설정 해줘야 함)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.252.26.32:3306/jihyuntest?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: cetus
    password: ecclesia8*

  #-- 사용할 DB 명시(Access to DialectResolutionInfo cannot be null when ‘hibernate.dialect’ not set )
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
#  jpa:
#    database: mysql
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true

